--ZO_CreateStringId("SI_BINDING_NAME_FCOCO_SHOW_COMPANION_MENU", GetString(FCOCO_SHOW_COMPANION_MENU))
if not FCOCO.isCompanionUnlocked then return end
ZO_CreateStringId("SI_BINDING_NAME_FCOCO_TOGGLE_COMPANION",     GetString(FCOCO_TOGGLE_COMPANION))
ZO_CreateStringId("SI_BINDING_NAME_FCOCO_TOGGLE_COMPANION_1",   GetString(FCOCO_TOGGLE_COMPANION_1))
ZO_CreateStringId("SI_BINDING_NAME_FCOCO_TOGGLE_COMPANION_2",   GetString(FCOCO_TOGGLE_COMPANION_2))
